import { Sidebar } from "@/components";
import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Harry Potter db Created with Next App",
  description: "Generated by create next app",
};

export default function CategoriesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <div className="bg-slate-100 overflow-y-scroll w-screen h-screen antialiased text-slate-300 selection:bg-blue-600 selection:text-white">
          <div className="flex ">
            <Sidebar />

            <div className="flex items-center justify-center w-full text-slate-900">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
